apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: svm-calico
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: svm/calico
    repoURL: https://github.com/outscale-vbr/argocd-stack.git 
    targetRevision: HEAD